---
title: "Formation-R-initiation"
subtitle: "Formation R initiation"
date: today
date-format: "DD/MM/YYYY"
author: "SSP/DEMESIS"
description: |
  Support de formation R-initiation au MASA
slide-tone: false # for blind readers
chalkboard: false # press the B key to toggle chalkboard
transition: slide
fig-cap-location: bottom
toc: true
toc-title: Sommaire
toc-depth: 1
toc-float: true
# multiplex: true
execute:
  echo: false
  warning: false
  cache: false
editor:
  render-on-save: true
  markdown: 
    wrap: 72
---

## Avant-propos

<br>

Ce diaporama de formation a été rédigé dans le but d'être le support
visuel des formations dispensées au
[MASA](https://agreste.agriculture.gouv.fr/).

Ces formations s'adressent à des agents qui ont suivi **les fondamentaux
de la programmation**.\

## Avant-propos

Elles sont données en présentiel sur une durée **de 2 jours**.

::: callout-note
## Champ couvert par cette formation

**Ce support couvre une initiation au language R avec R-studio et une
découverte de l'environnement de production du MASA.**

Pour information, les thêmes abordés sont:

-   01 - Présentation

-   02 - Les objets de R

-   03 - Manipulation et traitement de données

Ils sont orientés pour être utile aux agents du SSM Agriculture et se
concentrent sur une utilisation de R via
[RStudio](https://posit.co/download/rstudio-desktop/) qui est mise à
disposition des agents sur la plateforme interne Cerise basée sur
RStudio Workbench.
:::

{{< include 01_presentation.qmd >}}

{{< include 02_objets.qmd >}}
